# Generated by Django 4.2.7 on 2024-03-13 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_habits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Если активно, уведомления будут приходить",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Опишите какую конечную цель вы преследуете, выполняя эти привычки",
                        max_length=150,
                        verbose_name="Описание цели",
                    ),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        default="Europe/Moscow",
                        help_text="Укажите часовой пояс по которому будут формироваться уведомления",
                        use_pytz=False,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "habits",
                    models.ManyToManyField(
                        help_text="Выберите привычки, которые хотите выполнять",
                        related_name="notification",
                        to="app_habits.habit",
                        verbose_name="Привычки",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
        ),
    ]
