# Generated by Django 4.2.7 on 2024-03-15 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_habits", "0002_habitnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodic",
            field=models.SmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
                verbose_name="Периодичность в днях",
            ),
        ),
    ]
